### ISSUE TITLE
多GPU推理与训练

### ISSUE THREAD

**Issue by lorihuang** [datawhalechina/self-llm#197]
各位大佬好，我是LLM的新手。请问下如果我想使用多GPU进行Gemma-2-9b-it FastApi 部署调用时应该如何修改api.py文件？假定我有4块闲置的GPU，每块GPU有8G显存，请问能否实现？能不能提供一个关于多GPU的推理、langchain以及微调的版本，以便知晓LLM应用全流程的多GPU版本教程，最好是Chinese-LLaMA-3这个模型的，如果不方便，其他模型也可以。万分感谢！

**Comment by lorihuang** [comment]
我刚尝试着修改了AutoModelForCausalLM.from_pretrained()里面的参数，增加了一个关键字参数
`max_memory={0:"8GB", 1:"8GB", 2:"8GB", 3:"8GB"},`
当我运行`python api.py`时，它能够顺利的完成加载，加载信息如下：
```
(llm-py310-torch212) [root@k8s-node4 gemma-2-9b-it]# python api.py 
Creat tokenizer...
Creat model...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.30s/it]
INFO:     Started server process [62664]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
```
但是当我给该端口发送POST请求时，报了以下错误：
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/llm/autodl-tmp/LLM-Research/gemma-2-9b-it/api.py", line 38, in create_item
    outputs = model.generate(input_ids=inputs.to(model.device), max_new_tokens=150)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 1068, in forward
    outputs = self.model(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 908, in forward
    layer_outputs = decoder_layer(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 650, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3.2023/envs/llm-py310-torch212/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 582, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cutlassF: no kernel found to launch!
```

**Comment by lorihuang** [comment]
btw，运行完python api.py后，查看显卡情况，输出如下：
```
Tue Jul  9 14:45:56 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P4                       Off |   00000000:3B:00.0 Off |                    0 |
| N/A   35C    P0             22W /   75W |    4883MiB /   7680MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla P4                       Off |   00000000:86:00.0 Off |                    0 |
| N/A   32C    P0             23W /   75W |    5401MiB /   7680MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  Tesla P4                       Off |   00000000:AF:00.0 Off |                    0 |
| N/A   33C    P0             22W /   75W |    5401MiB /   7680MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  Tesla P4                       Off |   00000000:D8:00.0 Off |                    0 |
| N/A   32C    P0             22W /   75W |    2377MiB /   7680MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     63032      C   python                                       4880MiB |
|    1   N/A  N/A     63032      C   python                                       5398MiB |
|    2   N/A  N/A     63032      C   python                                       5398MiB |
|    3   N/A  N/A     63032      C   python                                       2374MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by KMnO4-zx** [comment]
将此处的 device_map 修改为 auto就可以了。它会自动给每块GPU分配显存空间。

<img width="620" alt="image" src="https://github.com/datawhalechina/self-llm/assets/77671993/8ed98022-5846-47c0-8386-e992e8eee301">

**Comment by KMnO4-zx** [comment]
但是考虑到你的显卡P4 可能不支持bf16格式，可以尝试使用fp16

**Comment by lorihuang** [comment]
@KMnO4-zx 嗖嘎，我现在就去尝试下，谢谢！

> 但是考虑到你的显卡P4 可能不支持bf16格式，可以尝试使用fp16

**Comment by lorihuang** [comment]
@KMnO4-zx 成了！输出如下：
```
(llm-py310-torch212) [root@k8s-node4 gemma-2-9b-it]# vim api.py    
(llm-py310-torch212) [root@k8s-node4 gemma-2-9b-it]# python api.py 
Creat tokenizer...
Creat model...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.25s/it]
INFO:     Started server process [73492]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
[2024-07-09 16:19:58] ", prompt:"<bos><start_of_turn>user
你好<end_of_turn>
<start_of_turn>model
", response:"'\n你好！   \n\n有什么我可以帮你的吗？ '"
INFO:     192.168.6.59:55477 - "POST / HTTP/1.1" 200 OK
```
万分感谢！微调那一块有什么需要修改的吗？

**Comment by lorihuang** [comment]
训练过程损失一直显示为0正常吗？
![image](https://github.com/datawhalechina/self-llm/assets/26337878/bfc9e090-6475-4b64-a954-38e88d59fd1e)

**Comment by lorihuang** [comment]
@KMnO4-zx 您好！不好意思又要打扰到您！
昨晚跑了2个多小时，今早使用checkpoint-1500跑预测出来的全是<pad><pad><pad><pad>……，应该还是训练过程中损失值为0造成的。检查了下代码，感觉还是多卡训练显存不足造成的，同样的代码丢到AutoDL中就是正常的，训练损失从4开始逐步下降。
我看到模型在定义参数时指定了`per_device_train_batch_size=1,`，我的理解是每一个GPU要负责一个batch_size的训练，但是我的一个GPU只有8G显存，就算是我在定义时指定了`device_map="auto"`，但仍然无法支撑对吧？如果想要修改代码，能否实现4个8G卡正常训练？
再次抱歉，万分感谢！

**Comment by KMnO4-zx** [comment]
loss为0，一般来说有两个原因

- transformers、peft或torch cuda 以来有问题
- 混合精度的锅，可以尝试吧lora参数转化为32位精度试试

因为在autodl上可以正常训练的话，很大可能是混合精度训练和依赖的问题

<img width="662" alt="image" src="https://github.com/datawhalechina/self-llm/assets/77671993/ede8cc2a-e220-4f47-ae44-9039f03ccbee">

希望这个回答对你有帮助～

**Comment by lorihuang** [comment]
> 以正常训练的话，很大可能是混合精度训练和依赖的问题

好的，我试一下，谢谢！

**Comment by lorihuang** [comment]
@KMnO4-zx 
![image](https://github.com/datawhalechina/self-llm/assets/26337878/f3425fa5-e3ad-4dcb-a8cb-daaf7b900a12)
已经能够正常训练了，您能提供一个LLM的学习路径吗？在这一块我就是个小白，以前也只接触过少量的图形图像处理，基本也是用tf做的，torch不了解，NLP基本没接触，现在想学习LLM，但有无从下手的无力感。
