### ISSUE TITLE
江湖救急，谢谢各位大佬

### ISSUE THREAD

**Issue by chinlee1523** [datawhalechina/self-llm#210]
Some parameters are on the meta device device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/root/DYLLM/fine-tuning/train.py", line 19, in <module>
    model = model.to_empty(device=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1036, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1036, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device), recurse=recurse)
  File "/usr/local/lib/python3.10/dist-packages/torch/_prims_common/wrappers.py", line 252, in _fn
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_refs/__init__.py", line 4875, in empty_like
    return torch.empty_permuted(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 130.00 MiB. GPU

**Comment by KMnO4-zx** [comment]
>  CUDA out of memory. Tried to allocate 130.00 MiB. GPU

显存不够大～
