### ISSUE TITLE
glm4 AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'chat'

### ISSUE THREAD

**Issue by eason9494** [datawhalechina/self-llm#245]
按照 01-GLM-4-9B-chat FastApi 部署调用.md 调用报错
INFO:     127.0.0.1:13068 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\anaconda3\envs\glm4\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\glm4\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\glm4\Lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\anaconda3\envs\glm4\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\anaconda3\envs\glm4\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\glm4\Lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\glm4\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\project\glm4-api\api.py", line 36, in create_item
    response, history = model.chat(
                        ^^^^^^^^^^
  File "D:\anaconda3\envs\glm4\Lib\site-packages\torch\nn\modules\module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'chat'
和教程的区别是模型从魔搭上下载的

**Comment by hongmin118** [comment]
我之前按教程搭的，也报这个错，执行`pip install --upgrade transformers`就可以了。
今天在autodl下新租了台机器，结果执行仍然抛错，懵逼了。。。

**Comment by aivike** [comment]
我也碰到了，有解决思路吗？
