### ISSUE TITLE
uvicorn running之后，点击网页，之后显示”目前无法处理此请求“，有没有赛博神医救救

### ISSUE THREAD

**Issue by crow-1412** [datawhalechina/self-llm#270]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/miniconda3/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f078f05b2f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=6006): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f078f05b2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/api-requests.py", line 11, in <module>
    print(get_completion('你是谁呀？'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/api-requests.py", line 7, in get_completion
    response = requests.post(url='http://127.0.0.1:6006', headers=headers, data=json.dumps(data))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=6006): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f078f05b2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by crow-1412** [comment]
我看的是这个教程：models/CharacterGLM/02-CharacterGLM-6B FastApi部署调用.md

**Comment by crow-1412** [comment]
![image](https://github.com/user-attachments/assets/a36d48d7-2aac-4760-8f35-1e5fd632cb6d)

**Comment by crow-1412** [comment]
## 配置
![image](https://github.com/user-attachments/assets/6fa04028-1faa-4f2a-bf55-b45a8042d708)

**Comment by crow-1412** [comment]
## 就这块点这个连接之后是打不开网页的，是不是要等一会再点？？
![image](https://github.com/user-attachments/assets/6d711a5c-1c7b-4797-8edb-ef14b71b9570)

**Comment by crow-1412** [comment]
> ## 就这块点这个连接之后是打不开网页的，是不是要等一会再点？？
> ![image](https://private-user-images.githubusercontent.com/141846839/378194391-6d711a5c-1c7b-4797-8edb-ef14b71b9570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzMwMjMsIm5iZiI6MTcyOTQzMjcyMywicGF0aCI6Ii8xNDE4NDY4MzkvMzc4MTk0MzkxLTZkNzExYTVjLTFjN2ItNDc5Ny04ZWRiLWVmMTRiNzFiOTU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMzU4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDEzOWI0NGUyYjU4YzU3MjVkYjc1ZjllYjkzNTg4NTNkMTU5MDVmYTM4ZWRjNDc5MjI2NWNmZjliZmIxZjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mGIC-F3b_YzXXdRP4LjI18lbJbd4S1x9ezaZfIV05Jo)

哦好像是要等会，我等会再看看

**Comment by crow-1412** [comment]
![image](https://github.com/user-attachments/assets/25a70a71-e6f0-49e3-8ffb-27b094aff019)

**Comment by crow-1412** [comment]
![image](https://github.com/user-attachments/assets/daa8339e-7e7e-4ef2-93b9-7c219818f76e)

**Comment by crow-1412** [comment]
![image](https://github.com/user-attachments/assets/bb5d1ec5-683e-435a-85e5-7ee0974ad1c5)
我自己弄出来了，ok解决了
