### ISSUE TITLE
运行train.py，下载的LLM-Research/Meta-Llama-3.1-8B-Instruct，缺少config文件

### ISSUE THREAD

**Issue by daydayup0206** [datawhalechina/self-llm#314]
Traceback (most recent call last):
  File "e:\new-learning\LLM\self-llm\examples\Chat-ll\train.py", line 27, in <module>
    model = AutoModelForCausalLM.from_pretrained(r'E:\new-learning\LLM\self-llm\examples\Chat-ll\autodl-tmp\LLM-Research', device_map="cuda",torch_dtype=torch.bfloat16)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat-zhenghuan\Lib\site-packages\transformers\models\auto\auto_factory.py", line 524, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat-zhenghuan\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 972, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat-zhenghuan\Lib\site-packages\transformers\configuration_utils.py", line 632, in get_config_dict  
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat-zhenghuan\Lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict 
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "D:\anaconda\envs\chat-zhenghuan\Lib\site-packages\transformers\utils\hub.py", line 373, in cached_file
    raise EnvironmentError(
OSError: E:\new-learning\LLM\self-llm\examples\Chat-ll\autodl-tmp\LLM-Research does not appear to have a file named config.json. Checkout 'https://huggingface.co/E:\new-learning\LLM\self-llm\examples\Chat-ll\autodl-tmp\LLM-Research/tree/None' for available files.

**Comment by daydayup0206** [comment]
解决了

**Comment by KMnO4-zx** [comment]
好的
